# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11d514beb84dea08545c08dae96d257b3e001f9df58480c37aa96ca04d9c0435b5916d70666ebefef59b1dcac3eb74e271b06cdfc0f372e272af0f89834b5f76

test:
  secret_key_base: 608f0c697bceb7f0ae3429d2c134bdd7b54b8efa046e650b3ab67f1b9f311df921072f465f7349e3f9c47c96821a3e6b4844b6b8c41f9ff19071cad784c28588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
